name: project_counselling
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  foundation: ^0.0.5
  get: ^4.7.2
  speech_to_text: ^7.0.0
  flutter_tts: ^4.2.3
  lottie: ^3.3.1
  google_generative_ai: ^0.4.7
  json_annotation: ^4.9.0
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.9
  intl: ^0.18.1 # Added intl package
  flutter_dotenv: ^5.1.0
  audioplayers: ^6.5.1
  shimmer_animation: ^2.2.2
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  google_sign_in: ^6.1.5
  cloud_firestore: ^5.6.11
  sqflite: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  json_serializable: ^6.8.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/lottie/
    - assets/images/
    - assets/icons/
    - assets/config/
    - assets/sounds/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik/Rubik-Light.ttf
          weight: 300

